// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmzjkukneotbesnkwiil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtemprdWtuZW90YmVzbmt3aWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxOTEyMDEsImV4cCI6MjA3NTc2NzIwMX0.NVhDiUG6nnX4leHEnmhqbmsrrwwSVLmzvEzMn72tTLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});